### ISSUE TITLE
Steuerung per "Target position" in %

### ISSUE THREAD

**Issue by DirtyAtze** [Excodibur/ioBroker.tahoma#1]
Im homebridge-tahoma Adapter ist die Steuerung von Rollläden/Jalousien über die Angabe einer Ziel-Position in % möglich.
Es wäre schön, wenn das auch im ioBroker TaHoma Adapter möglich wäre.

![TaHoma](https://user-images.githubusercontent.com/52576302/72507194-b80c4e80-3843-11ea-9ce8-0aa2a4d16e24.jpg)

**Comment by StrathCole** [comment]
Hi,

das ist möglich.
Einfach unter "states" die Werte `core:ClosureState`, `core:TargetClosureState` oder `core:SlateOrientationState` ändern (ack = false).

**Comment by DirtyAtze** [comment]
Ok, funktioniert! Danke für den Tipp!
