### ISSUE TITLE
Queue 

### ISSUE THREAD

**Issue by Melonenyoshi** [Excodibur/ioBroker.tahoma#10]
i want to delete the queue everytime you press for example down
because when i dont do this and someone presses more then 1 time the shutter starts a 2nd time if you stop the first attempt with the remote

**Comment by Excodibur** [comment]
Please provide a bit more information about the issue you are experiencing.

I assume you are trying to use commands like _down_, _up_, _stop_ to control your shutters. If I e.g. press _down_ two times, the first command closes the shutter, while the second click slows the movement down. Anyways I can still stop this process fully with the remote control button on the wall.

**Questions:**
- How does your scenario look exactly? 
- What kind of shutters are you using?
- Which adapter version do you use?
- Is there anything weird shown in the logs during that time?
