### ISSUE TITLE
incompatible device name

### ISSUE THREAD

**Issue by achbie** [Excodibur/ioBroker.tahoma#101]
It seems, that a device name e.g. "Esszimmer_RM_6,7" is not allowed. Maybe there is a problem by using the "comma" symbol.
All the other devices can be controlled without any problems. This device names are all without a "comma" symbol.

Thanks

Log:
(506) State "tahoma.0.devices.Esszimmer_RM_6_7.commands.down:slow" has no existing object, this might lead to an error in future versions
(506) Used invalid characters: tahoma.0.devices.Esszimmer_RM_6,7.commands.down:slow changed to tahoma.0.devices.Esszimmer_RM_6_7.commands.down:slow

Version:
- Adaper: 0.52
- JS-Controller: 3.3.22
- Node.JS: 14.18.1
- System: Ubuntu 21.04

**Comment by Excodibur** [comment]
It should be fixed now [v0.5.3](https://github.com/Excodibur/ioBroker.tahoma/releases/tag/v0.5.3). Please give it a try.

**Comment by achbie** [comment]
Thanks for the quick job. After deleting the old objects and restarting of the adapter it works all fine.
