### ISSUE TITLE
core:OnOffState

### ISSUE THREAD

**Issue by Lucascoco** [Excodibur/ioBroker.tahoma#106]
I can not change the state, Only in expert Modus i can write on, but i has no effet,
What make i wrong?

THX

**Comment by Excodibur** [comment]
I think this is not supported by the adapter yet, but I will check what can be done here.

**Comment by Excodibur** [comment]
Please check if it works better with [Release 0.5.5](https://github.com/Excodibur/ioBroker.tahoma/releases/tag/v0.5.5).

**Comment by Lucascoco** [comment]
Sry for my bad skils, but i cant see the package in the iobrocker, how can i update the adapter?

**Comment by Lucascoco** [comment]
THX, it works. But i can only change the state in expert mode.

**Comment by Excodibur** [comment]
Thx for the feedback! I think I see the issue you are describing. Please give it another try with [Release 0.5.6](https://github.com/Excodibur/ioBroker.tahoma/releases/tag/v0.5.6).

**Comment by Lucascoco** [comment]
i can update the apdaper over github, but when i restart the adapter it will go back to 0.5.5.

**Comment by Excodibur** [comment]
This is weird.

If you have access to iobroker installation via shell, you could also install the latest release directly from npm:
```
cd /opt/iobroker/
npm install iobroker.tahoma@~0.5.6
#optional, if no instance exists yet:
# iobroker add tahoma
```

**Comment by Lucascoco** [comment]
i have reboot my pi, now version is 0.5.6.
But i can change the state in normal Mode.
And now it dont work in expert mode.

**Comment by Excodibur** [comment]
I assume by "Expert Mode" you mean the expert-view in Admin. With Admin 5.3.1 (modern UI) I am able to change the state, regardless of which mode is used. So I can't really reproduce your latest issue - perhaps it is an issue with Admin-adapter, rather than this Tahoma Adapter.

**Comment by Lucascoco** [comment]
when i click on the state i get this
![Image 249](https://user-images.githubusercontent.com/101245521/158560880-86f3961b-a0fa-4ff1-bbe6-6dbbf81df5d9.png)

**Comment by Excodibur** [comment]
Your screenshot shows what happens when you try to edit (red section) the state-metadata, like _Type_ and _Role_ which should not be modified manually, as the adapter likely will override those at any time.

The **value** of the state (green section) is changed by clicking directly onto the value, or using ioBroker cli commands or Java-functions. This should work both in and out of expert mode and this is what is sent to Tahoma servers to change the behaviour of your devices.

![image](https://user-images.githubusercontent.com/70700967/158564830-103ccf33-e2a1-43fd-b2ff-ff70250c4566.png)

**Comment by Lucascoco** [comment]
i cant click direct on the green section. nothing happens

**Comment by Excodibur** [comment]
Honestly this sounds like a bug in the admin-adapter (or some adblocker interupting something here), rather than this adapter, as the dialog window to my knowledge always should pop up.

You could also check if the state could be set directly via iobroker CLI via:
```
#need to use your own unique state-id here of course
iobroker state set tahoma.0.devices.Adapter_Plug_IO.states.core:OnOffState off
```

**Comment by Lucascoco** [comment]
sry, over cli it dont work
and i also try the edge and the chrome broswer both the same, but every other data point i can change the true oder false state

**Comment by Excodibur** [comment]
Please provide some details about the cli-command you used. How does it look like? What is the response sent from iobroker?

**Comment by Lucascoco** [comment]
iobroker state set tahoma.0.devices.LIGHT_VAR_io.states.core:OnOffState false

The state "tahoma.0.devices.LIGHT_VAR_io.states.core:OnOffState" was set to "false" with flag ack=false

**Comment by Excodibur** [comment]
Ok so in that case iobroker says it changed the state successfully.

One problem here is, that this specific state only can have the values **on** or **off**, not **true** of **false**. This is defined that way by the Tahoma-API. I assume that if you set it to false, the adapter will try to send it to Tahomalink where it probably is rejected as invalid parameter value.

**Comment by Lucascoco** [comment]
when i type on and off, there will be the same

**Comment by Excodibur** [comment]
Yeah ok, but are there any logmessages in Tahoma-Adapter that indicate any technical issues? According to the output you provided ioBroker is able to change the state, so the only thing I could think of is that there might be some problem with applying the changed value to Tahomalink.

If there are no errors visible, may I ask you to please provide DEBUG logs to me from your Tahoma Adapter instance, ideally also covering the time-period where you attempt to change the state? As those might be quite big, you can also send them to me directly via [excodibur-iobroker@posteo.de](mailto:excodibur-iobroker@posteo.de).
