### ISSUE TITLE
uncaught exception: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by nummerxiv** [Excodibur/ioBroker.tahoma#118]
I'm on **Version 6.1.3** and have **oximo io shutters** installed. Lately the adapter is being **_terminated_** because of the following error:

**uncaught exception: Cannot read property 'length' of undefined**

`TypeError: Cannot read property 'length' of undefined at /opt/iobroker/node_modules/iobroker.tahoma/lib/tahoma.js:957:37 at Request._callback (/opt/iobroker/node_modules/iobroker.tahoma/lib/tahoma.js:331:17) at Request.self.callback (/opt/iobroker/node_modules/request/request.js:185:22) at Request.emit (events.js:400:28) at Request.<anonymous> (/opt/iobroker/node_modules/request/request.js:1154:10) at Request.emit (events.js:400:28) at IncomingMessage.<anonymous> (/opt/iobroker/node_modules/request/request.js:1076:12) at Object.onceWrapper (events.js:519:28) at IncomingMessage.emit (events.js:412:35) at endReadableNT (internal/streams/readable.js:1334:12)`

Thanks for your help and good work you are putting into this adapter.

[‎192.168.1.30:8081:log:buanet-iobroker1:file1:iobroker.2022-04-03.pdf](https://github.com/Excodibur/ioBroker.tahoma/files/8404364/192.168.1.30.8081.log.buanet-iobroker1.file1.iobroker.2022-04-03.pdf)

**Comment by Excodibur** [comment]
I assume you mean v.0.6.1, right?

May I ask you to set the loglevel to DEBUG and provide the (redacted) logs either in this ticket, or via mail to me ([excodibur-iobroker@posteo.de](mailto:excodibur-iobroker@posteo.de)?

**Comment by nummerxiv** [comment]
The error is not occurring since today. Im not sure what has changed. I will keep an eye on it and comment as soon as its coming up.

Thanks for your fast response.

**Comment by Excodibur** [comment]
ok, I'll wait for further input from you then 😃

**Comment by nummerxiv** [comment]
Hi im not sure what is happening here but its not working at all anymore. I would appreciate help 😄 

tahoma.0 | 2022-05-19 16:00:34.210 | debug | stateChange tahoma.0.info.connection {"val":true,"ack":true,"ts":1652968834207,"q":0,"from":"system.adapter.tahoma.0","user":"system.user.admin","lc":1652968804145}
-- | -- | -- | --
tahoma.0 | 2022-05-19 16:00:34.201 | debug | Will attempt again to login in 30 seconds.
tahoma.0 | 2022-05-19 16:00:34.200 | warn | error during tahomalink request: ->401 retry login
tahoma.0 | 2022-05-19 16:00:34.099 | debug | POST request on https://www.tahomalink.com/enduser-mobile-web/enduserAPI/login with payload: +++redacted+++
tahoma.0 | 2022-05-19 16:00:34.098 | info | Login attempt #1
tahoma.0 | 2022-05-19 16:00:04.149 | debug | stateChange tahoma.0.info.connection {"val":true,"ack":true,"ts":1652968804145,"q":0,"from":"system.adapter.tahoma.0","user":"system.user.admin","lc":1652968804145}
tahoma.0 | 2022-05-19 16:00:04.098 | debug | Will attempt again to login in 30 seconds.
tahoma.0 | 2022-05-19 16:00:04.097 | warn | error during tahomalink request: ->401 retry login
tahoma.0 | 2022-05-19 16:00:04.018 | debug | stateChange tahoma.0.update {"val":false,"ack":true,"ts":1652968804013,"q":0,"from":"system.adapter.tahoma.0","user":"system.user.admin","lc":1648648533693}
tahoma.0 | 2022-05-19 16:00:03.796 | debug | POST request on https://www.tahomalink.com/enduser-mobile-web/enduserAPI/login with payload: +++redacted+++
tahoma.0 | 2022-05-19 16:00:03.793 | debug | [START] Started Adapter
tahoma.0 | 2022-05-19 16:00:03.792 | info | Configured polling interval: 20000
tahoma.0 | 2022-05-19 16:00:03.791 | info | [START] Starting adapter tahoma v0.6.1.3
tahoma.0 | 2022-05-19 16:00:03.690 | debug | Schedule restart: 0 16 * * *
tahoma.0 | 2022-05-19 16:00:03.605 | info | starting. Version 0.6.1 (non-npm: Excodibur/ioBroker.tahoma) in /opt/iobroker/node_modules/iobroker.tahoma, node: v14.19.1, js-controller: 4.0.23
host.buanet-iobroker1 | 2022-05-19 16:00:01.694 | info | instance system.adapter.tahoma.0 started with pid 7100
host.buanet-iobroker1 | 2022-05-19 16:00:00.629 | info | Restart adapter system.adapter.tahoma.0 because enabled
host.buanet-iobroker1 | 2022-05-19 16:00:00.628 | info | instance system.adapter.tahoma.0 scheduled normal terminated and will be restarted on schedule.
tahoma.0 | 2022-05-19 16:00:00.080 | info | Terminated (START_IMMEDIATELY_AFTER_STOP): Without reason
tahoma.0 | 2022-05-19 16:00:00.077 | info | terminating
tahoma.0 | 2022-05-19 16:00:00.067 | info | Scheduled restart.

**Comment by Excodibur** [comment]
Your Somfy (Tahoma) account is likely locked, which happens from time to time. Only way to solve this is usually deactivating the adapter and waiting at least a day for Somfy to unlock the account again. Usually during the time the account is locked you are also not able to login directly to tahomalink.com.
