### ISSUE TITLE
updates only at startup

### ISSUE THREAD

**Issue by Daniel210117** [Excodibur/ioBroker.tahoma#119]
Hello,

I have the newest adapter plugin 0.6.1. The Tahoma Box has also the newest firmware.
The adapter start and login to tahoma. All OK, all green.
But the commands don't work (open, close etc.).
The next problem are the state. If I open or close the blind (with tahoma app), the levels never update.
But only if I restart the plugin, the levels are update correctly.
What can I do?

**Comment by Excodibur** [comment]
Hi Daniel,

unfortunately, for me the commands work fine. May I ask you to provide some DEBUG-logs, so I can take a closer look on what is happering on your side?

The percentages for blinds should change, but it also depends on the _Polling Interval_ you set in your adapter config, which is the time-period after which "fresh" values are fetched.
