### ISSUE TITLE
No device datapoints - no reaction

### ISSUE THREAD

**Issue by zeron850** [Excodibur/ioBroker.tahoma#120]
Dear Developer,

thank you for very much for your afforts in the developing of a Somfy Tahoma Adapter. Actually i installed new the adapter, but there create no datapoints for the devices, as well the states.

Could you fix the problem?

ThX
![Screenshot 2022-04-18 172659](https://user-images.githubusercontent.com/68141401/163831643-85f4b263-2d6a-428c-9a37-ebcf1427738b.png)
![Screenshot 2022-04-18 172720](https://user-images.githubusercontent.com/68141401/163831646-1d087ce8-aa22-427e-9960-89a11da7dbb1.png)
![Screenshot 2022-04-18 172735](https://user-images.githubusercontent.com/68141401/163831649-29d05021-6acb-4a6a-99c3-007f901da408.png)

**Comment by Excodibur** [comment]
It looks like your account is locked. Please deactivate the adapter for at least a day, to give the account time to unlock.

Please try again afterwards.🙂

**Comment by zeron850** [comment]
Ok thx i‘ll try it 🙉
