### ISSUE TITLE
Ständige Verbindungsprobleme

### ISSUE THREAD

**Issue by Supermario-21** [Excodibur/ioBroker.tahoma#137]
Jeden zweiten Tag verliert der Adapter die Verbindung. Teilweise helfen erst mehrmalige Neustarts.  
Das Protokoll ist voll davon:  error during tahomalink request: ->401 retry login

Version v0.6.1
Boxversion 2022.2.4-13

**Comment by nummerxiv** [comment]
Das selbe Problem habe ich leider auch seit einiger Zeit. Lässt sich auch oft nicht beheben. Ich denke aber leider, dass das Problem bei Somfy liegt. Man könnte es ggf. umgehen wenn man die Anzahl der Anfragen senkt oder versucht direkt auf die Tahoma Box zu kommen und nicht über die API von deren Server geht. Hierzu kenne ich aber die technischen Gegebenheiten zu schlecht.

**Comment by Supermario-21** [comment]
Über HomeKit ist die Zuverlässigkeit zur Somfy-Box grösser. Aber natürlich nicht alle Geräte HK-kompatibel. Seit dem Update von der Somfy-Box vor 3 Wochen eine einzige Katastrophe. Draussen ist Strum und meine Markise ist immer noch voll geöffnet oder sagt man doch geschlossen :-)

**Comment by Supermario-21** [comment]
Wo sieht man im Datenpunkt, dass die Anmeldung nicht funktioniert? Bei mir steht alles auf "true", obwohl das Protokoll voll mit Fehlermeldungen ist!

**Comment by TrifusOnline** [comment]
Ich habe in der Tat seit einigen Tagen leider das selbe Problem.
Tahoma Box: Version 2022.2.4-13.

Mit der lokalen API will sich der Adapter leider auch nicht verbinden.

**Comment by nummerxiv** [comment]
> Ich habe in der Tat seit einigen Tagen leider das selbe Problem. Tahoma Box: Version 2022.2.4-13.
> 
> Mit der lokalen API will sich der Adapter leider auch nicht verbinden.

Ist es überhaupt möglich mit dem Adapter auf die lokale API zu gehen? Ich habe etwas von nem DEV Modus gelesen, bei dem ne lokale API frei geschaltet werden kann. Finde aber leider keine Möglichkeit den zu aktivieren

**Comment by TrifusOnline** [comment]
Ich habe es gefunden. Die Lokale API schaltest Du über: somfy.de Mein Konto unten links frei. Verbindet sich tadellos.

**Comment by nummerxiv** [comment]
> Ich habe es gefunden. Die Lokale API schaltest Du über: somfy.de Mein Konto unten links frei. Verbindet sich tadellos.

Wie genau funktioniert das? Ich schalte den Entwicklermodus an und dann? Ich kann ja nirgends ne IP eingeben in der IO Broker Instanz. Für ein bisschen Hilfe wäre ich sehr Dankbar :)

**Comment by nummerxiv** [comment]
> > Ich habe es gefunden. Die Lokale API schaltest Du über: somfy.de Mein Konto unten links frei. Verbindet sich tadellos.
> 
> Wie genau funktioniert das? Ich schalte den Entwicklermodus an und dann? Ich kann ja nirgends ne IP eingeben in der IO Broker Instanz. Für ein bisschen Hilfe wäre ich sehr Dankbar :)

Habs. Einfach den Expertenmodus einschalten, dann erscheint ein weiterer TAB in den Einstellungen.

**Comment by SamLowrie** [comment]
Muss nochmal dumm nachfragen: Ich hab im Somfy Webinterface den Entwicklermodus aktiviert und die dort angezeigte PIN in der Adapter-Config im Reiter "Lokale API Einstellungen" eingegeben. 
Das hat aber noch keine Änderung gebracht?! Im Expertenmodus sehe ich auch keine weiteren Einstellmöglichkeiten. Wo kann man eine IP eingegeben? MDNS habe ich aus ein eingeschaltet, allerdings sehe ich keine passenden Broadcast-Anfragen raus gehen?

Nachtrag:
Schalte ich den Debug-Mode ein, sagt er zwar, dass er die lokale API benutzt, will sich dann aber zu https://ha101-1.overkiz.com/... verbinden und bekommt einen  "error during request: ->401 retry login".

**Comment by Excodibur** [comment]
Das Konfigurieren der PIN unter _Lokale API Einstellungen_ sollte reichen (sofern der Adapter danach auch neugestartet wurde). Der Adapter verbindet sich dann auf folgendem Hostnamen in deinen lokalen Netzwerk: `gateway-<deine gatewaypin>`. Wenn du MDNS  an hast, dann hängt er noch ein `.local` als domain an, was bei einigen Routern (z.B. FritzBox) zu Problemen mit der Namensauflösung (DNS) führt - daher habe ich bei mir das auch immer deaktiviert.

D.h. eine IP-Adresse kannst du nirgendwo im Adapter konfigurieren, weil dieser sich drauf verlässt, dass dein Host-System den oben genannten Hostnamen selbst auflösen kann. Funktioniert das aus irgendwelchen Gründen nicht, könntest du auch den obigen Hostnamen + die IP des Gateways (kann man beim Router in der Regel in der Liste der verbunden Netzwerkgeräte sehen) in die _hosts_ Datei des Systems wo IOBroker läuft, eintragen. Dann wird den Namensauflösung auf jeden Fall funktionieren.

**Comment by SamLowrie** [comment]
Vielen Dank für die Erklärung.

Leider funktioniert es immer noch nicht korrekt. Ich habe im IOBroker Docker-Container in die hosts-Datei die Namenseinträge hinzugefügt (zur Sicherheit mit/ohne .local und mit/ohne Bindestrich). Ping auf den Namen funktioniert auch. Allerdings scheint immer noch keine Verbindung mit der Box aufgebaut zu werden:

```
Adapter will connect to Tahoma Box via local API.
POST request on https://ha101-1.overkiz.com/enduser-mobile-web/enduserAPI/login with payload: +++redacted+++
stateChange tahoma.0.update {"val":false,"ack":true,"ts":1654986376154,"q":0,"from":"system.adapter.tahoma.0","user":"system.user.admin","lc":1622842329828}
error during request: ->401 retry login
```

(Adapter Version ist 0.7.1, Login/Passwort sind geprüft)

**Comment by SamLowrie** [comment]
Es funktioniert jetzt! Ich habe den gesamten Docker-Container neu gestartet, jetzt funktioniert es (Dabei gab es auch ein Minor-Update des JS-Controllers und der Node-JS Version).
