### ISSUE TITLE
not working with node.js 12?

### ISSUE THREAD

**Issue by Moormerlander** [Excodibur/ioBroker.tahoma#14]
Since i upgraded to node.js from version 10 to 12 the adapter isn't working any more. The status is green but it accepts no commands any more.

**Comment by Excodibur** [comment]
Did you get a chance to check this problem again? For me it is working fine right now with Node 14, but automated tests currently also check that it works for 12 and 16, so generally speaking it should work.

If it still persists, please provide some debug-logs so I can analyze it more in depth.
