### ISSUE TITLE
Failed getting execution state on local api

### ISSUE THREAD

**Issue by nummerxiv** [Excodibur/ioBroker.tahoma#149]
Im connecting to the local API and it seems to work but im getting this warining all the time. Any idea?

tahoma.0 | 2022-06-12 19:51:21.651 | warn | Failed getting execution state for 44283f5a-12d9-4aaa-a8f6-9a48bab5086b
-- | -- | -- | --
tahoma.0 | 2022-06-12 19:51:21.651 | warn | Body: "{\"error\":\"Unknown object.\",\"errorCode\":\"UNSPECIFIED_ERROR\"}"
tahoma.0 | 2022-06-12 19:51:21.650 | warn | Response: {"statusCode":400,"body":"{\"error\":\"Unknown object.\",\"errorCode\":\"UNSPECIFIED_ERROR\"}","headers":{"content-type":"application/json","access-control-allow-origin":"*","access-control-allow-headers":"Authorization","content-length":"59","connection":"close","date":"Sun, 12 Jun 2022 17:51:21 GMT","server":"KizOs"},"request":{"uri":{"protocol":"https:","slashes":true,"auth":null,"host":"gateway-XXXX-XXXX-XXXX:8443","port":"8443","hostname":"gateway-XXXX-XXXX-XXXX","hash":null,"search":null,"query":null,"pathname":"/enduser-mobile-web/1/enduserAPI/history/executions/44283f5a-12d9-4aaa-a8f6-9a48bab5086b","path":"/enduser-mobile-web/1/enduserAPI/history/executions/44283f5a-12d9-4aaa-a8f6-9a48bab5086b","href":"https://gateway-XXXX-XXXX-XXXX:8443/enduser-mobile-web/1/enduserAPI/history/executions/44283f5a-12d9-4aaa-a8f6-9a48bab5086b"},"method":"GET","headers":{"User-Agent":"Mozilla/5.0 (X11; Linux x86_64; rv:79.0) Gecko/20100101 Firefox/79.0","Authorization":"Bearer 629de067aa395421346a","Content-type":"application/json"}}}
tahoma.0 | 2022-06-12 19:51:21.648 | warn | error during request: null, request path: history/executions/44283f5a-12d9-4aaa-a8f6-9a48bab5086b with payload:{}

**Comment by Excodibur** [comment]
It looks like the local API does not provide all endpoints the online-API supported in the past. At least "history" is not listed in the current API doc here: https://somfy-developer.github.io/Somfy-TaHoma-Developer-Mode/.

Looking at similar issues for non-existant endpoints "Unknown object" seems to be the general reply from the local API in those cases, e.g. https://github.com/Somfy-Developer/Somfy-TaHoma-Developer-Mode/issues/26.

Perhaps Somfy will add it in the future, but I'll check what can be done for now about it in the adapter.

**Comment by lonisgree** [comment]
Hi, I have the same problem. Is there a solution?

**Comment by Andy-47** [comment]
I have the same issue:

Describe the bug
Today I updated the Tahoma box to the lastet version. Now the Tohama adapter is throwing a package of 4 warnings to the protocoll.
Current version of tahoma adapter:
adapter tahoma v0.7.2.3
Version 0.7.2 (non-npm: Excodibur/ioBroker.tahoma) in /opt/iobroker/node_modules/iobroker.tahoma, node: v14.19.1, js-controller: 4.0.23

2022-07-12 13:24:10.059 | warn | Failed getting execution state for 9233ad1d-0b97-4944-b19b-d2004f234b31

tahoma.0 | 2022-07-12 13:24:10.058 | warn | Body: "{"error":"Unknown object.","errorCode":"UNSPECIFIED_ERROR"}"

tahoma.0 | 2022-07-12 13:24:10.057 | warn | Response: {"statusCode":400,"body":"{"error":"Unknown object.","errorCode":"UNSPECIFIED_ERROR"}","headers":{"content-type":"application/json","access-control-allow-origin":"*","access-control-allow-headers":"Authorization","content-length":"59","connection":"close","date":"Tue, 12 Jul 2022 11:24:10 GMT","server":"KizOs"},"request":{"uri":{"protocol":"https:","slashes":true,"auth":null,"host":"----deleted-------

2022-07-12 13:24:10.056 | warn | error during request: null, request path: history/executions/9233ad1d-0b97-4944-b19b-d2004f234b31 with payload:{}

I guess the long warning contains some access data. I delete this to publish the warning here.

Access via direct API.

Regards
Andreas

**Comment by Excodibur** [comment]
Should now be fixed with https://github.com/Excodibur/ioBroker.tahoma/releases/tag/v0.10.0.
