### ISSUE TITLE
Update auf Version 0.3.3

### ISSUE THREAD

**Issue by raspihomegit** [Excodibur/ioBroker.tahoma#15]
Hallo, 
ich nutze ioBroker erst seit kurzem und habe meine TaHoma verbunden.
Ich habe das Problem, dass meine Logins geblockt werden, obwohl ich die Abtastrate schon auf 300000 gestellt habe.
Nun dachte ich, dass ich den Adapter erst einmal auf die Version 0.3.3 updaten sollte.
Könnt ihr mir bitte verraten, wie dieses Update durchführen kann?

Grüße
raspihomegit

**Comment by Master-Rudi** [comment]
Ich habe seit Wochen das gleiche Problem.

Auch die 0.3.3 wird da nicht helfen leider. Ich weiß nicht woran es liegt, bin aber froh wenn es nicht nur mir so geht, man liest recht wenig über diesen Fehler.

**Comment by raspihomegit** [comment]
Ist schon komisch, dass manche eben schreiben, dass es keine Probleme gibt, obwohl die Abtastrate bei 10000 eingestellt. 

Ich hatte meinen iobroker zuerst auf einem win10 pc installiert. Ich bin der Meinung, dass der Fehler dort nicht so häufig aufgetreten ist. Nun habe ich meinen Raspberry PI 4 in Betrieb genommen und alles installiert. Und nun tritt der Fehler viel häufiger auf. Gestern hatte ich den Adapter neu gestartet und nach 10 min ging der Login Fehler wieder los. Ich verzweifle langsam.

**Comment by raspihomegit** [comment]
@meister-rudi

unabhängig vom Fehler. Wie hast du deinen Adapter auf die Version 0.3.3 gehoben? Welche Befehle muss ich da eingeben?

**Comment by Master-Rudi** [comment]
Ich betreibe es seit 1,5 Jahren auf meinem Raspbi Und es funktionierte bestimmt 8 Monate ohne Fehler, seit über einem halben Jahr geht es jetzt nicht mehr, hab den Adapter mittlerweile deaktiviert. Hab viel probiert aber keine Lösung gefunden. Ich hoffe es findet sich eine Lösung, habe mit die TaHoma nur für mein SmartHome gekauft

**Comment by raspihomegit** [comment]
Das heißt deine Tahoma Geräte nutzt du nicht mehr im ioBroker? Oder gibt es noch eine andere Möglichkeit, diese Geräte einzubinden?
Ich habe mir die Tahoma vor 4 Monaten gekauft und bin bisher sehr unzufrieden mit Somfy. Zumindest beim Thema Heizkörperthermostaten sind die keine "Pioniere im Smart Home Bereich".

**Comment by Master-Rudi** [comment]
![3621D52A-36A7-4BA4-B480-2B95314E4332](https://user-images.githubusercontent.com/23149266/104293695-97122400-54be-11eb-83c0-25e28b619763.jpeg)

relativ einfach: einfach ganz rechts klicken und die Version wählen die man haben will. Wenn sie da nicht drin steht dann mal die Pakete aktualisieren oder manuell installieren 

Im Moment nutze ich es gar nicht, nur mit der Somfy App. Aber steuere auch nur meine Rollläden damit und im Winter brauch ich das wenig. Für die alten RTS Rollos, die nicht mit der Somfy TaHoma kompatibel waren hab ich mir selber was gebaut und direkt in den ioBroker gebracht.

**Comment by raspihomegit** [comment]
OK, danke für die Info.

Wenn auf diesen Button klicke, steht nur die 0.3.2 zur Verfügung.
Sieht fast danach aus, dass die Version 0.3.3 wieder entfernt wurde.

Danke für deine Hilfe.
