### ISSUE TITLE
new 0.7.1 version doesn't work with Connexoon box anymore

### ISSUE THREAD

**Issue by Kaiman77** [Excodibur/ioBroker.tahoma#150]
The new version supports the local API, but the Connexoon box doesn't have the developer mode and thus no local API.
I don't get the new version of the adapter running with my Connexoon box.

It just says:
`error during request: Error: connect ECONNREFUSED 10.1.1.63:8443, request path: setup with payload:{}`
Which makes sense because the box doesn't allow local requests.

If I remove the local PIN, it comes with:
`tahoma.0 | 2022-06-15 16:50:03.907 | warn | error during request:  ->401 retry setup
-- | -- | -- | --`
`tahoma.0 | 2022-06-15 16:50:03.902 | warn | error during request:  ->401 retry actionGroups`
`tahoma.0 | 2022-06-15 16:50:03.729 | info | Using stored bearer token 62a6414bc3ddaefd2bd0`
any way to use the new 0.7.1 without local API for the Connexoon box?
The 0.6.1 works fine.

**Comment by Excodibur** [comment]
This local-password being used without having a gateway-pin set definitely is a bug. Please give it another try with https://github.com/Excodibur/ioBroker.tahoma/releases/tag/v0.7.2.

**Comment by Kaiman77** [comment]
ok, that one works :-)
Thanks for the fast solution.
