### ISSUE TITLE
adapter forgets password when restarted

### ISSUE THREAD

**Issue by Raabensohn** [Excodibur/ioBroker.tahoma#151]
I have to restart the adapter daily for it to work properly.
After the restart the the password-field is empty and the adapter does not start

**Comment by Excodibur** [comment]
Are you by any chance reading out and modifying the adapter configuration `/system/adapter/tahoma`, e.g. via JavaScript-adapter? I remember a similar case in the past (user had the idea to trigger adapter restarted by altering online-state in config) where this corrupted the password. The password itself is defined as a protected field, meaning that any attempt to modify the adapter configuration from the outside will corrupt the set password.

**Comment by Raabensohn** [comment]
you are right, that was the trick.
I restarted the adapter every night because it crashed very often before.
Let's see, how it will work now. :-)
Thanks!
