### ISSUE TITLE
'leise'-Modus Rollläden

### ISSUE THREAD

**Issue by Basti189** [Excodibur/ioBroker.tahoma#156]
Die aktuelle Generation Rollladenmotoren (RS100 io) haben einen 'leise'-Modus in welchem die Rollläden mit reduzierter Geschwindigkeit fahren und somit kaum hörbar sind. Diese Datenpunkte sind nicht vorhanden, wenn die lokale API genutzt wird. Unterstützt die lokale API diese Datenpunkte nicht? Es wäre schön, wenn diese wieder in dem Adapter zur Verfügung stehen würden.

**Comment by DirtyAtze** [comment]
Ich habe ebenfallst die RS100 Motoren verbaut.
Ich hatte den Adapter bis vor kurzem über die WebAPI laufen und habe dann auf die lokale API umgestellt.
Die 'leise' befehle funktionieren bei mir immernoch ohne probleme. Ich kann aber nicht sagen, ob sie über die lokale API automatisch erstellt werden.
Du könntest also versuchen, den Adapter erst mit der WebAPI zu verbinden, damit er die Datenpunkte erstellt und anschließend auf die lokale API umstellen. (Wäre zumindest ein Workaround)

Gruß

**Comment by Excodibur** [comment]
Da scheint sich etwas am Format der Daten bzgl. Local API geändert zu haben. Ich habe den Fehler hier im Repo schon angepasst (https://github.com/Excodibur/ioBroker.tahoma/commit/94eaa1c548471d2cdc8ed473a3ea46f4c1b88369), d.h. wenn ihr den Adapter nochmal direkt aus diesem Repo installiert, sollte es gehen. Ich schaue das es zeitnah auch einen neue offizielle Adapter-Version hierfür geben wird.

**Comment by Excodibur** [comment]
https://github.com/Excodibur/ioBroker.tahoma/releases/tag/v0.8.0 (oder neuer) sollte den Fix beinhalten.
