### ISSUE TITLE
Tahoma Adapter Fehler "no registered even listener"

### ISSUE THREAD

**Issue by raspihomegit** [Excodibur/ioBroker.tahoma#16]
warn | (1577) Body: {"errorCode":"UNSPECIFIED_ERROR","error":"No registered event listener"}
warn | (1577) Response: {"statusCode":400,"body":{"errorCode":"UNSPECIFIED_ERROR","error":"No registered event listener"},"headers":{"date":"Wed, 13 Jan 2021 13:18:09 GMT","server":"overkiz","strict-transpor
warn | (1577) error during tahomalink request: null, request path: events/fbe2b682-ac10-3e01-5645-036b8c382708/fetch with payload:{}

Ich bekomme diese Fehler in meinem Log einfach nicht weg.
Ich bin der Meinung, dass diese Fehler auftreten, seitdem ich auf der Somfy open API Webseite meinen Account mit OAuth2 authentifiziert habe.

Kennt jemand dafür eine Lösung?

Grüße

Raspihomegit

**Comment by AndreasExner** [comment]
+1 Ich finde auch keine Erklärung

**Comment by Excodibur** [comment]
Hmm, 400 deutet darauf hin, dass der Server (Tahomalink) die Anfrage des Adapters nicht versteht.

Wann tritt diese Meldung bei euch auf? Direkt nach dem Adapter-Start, oder nach mehreren Stunden oder sogar Tagen?

Wenn es wirklich am Adapter liegen sollte, stellt bitte noch DEBUG Logs bereit, damit ich mir genauer anschauen kann, was der Adapter schickt bevor es zu der Fehlermeldung kommt. Gerne auch an excodibur-iobroker@posteo.de

**Comment by AndreasExner** [comment]
Die Meldungen kommen immer mal wieder. Ich habe aber jetzt länger nicht reingesehen, da es grundsätzlich funktioniert. Ich schaue mir das die Tage nochmal an und sende ggf. die Log. Generell kann man aber sagen, dass in der letzten Zeit das Throttling der API schneller zuschlägt. Ich musste den Poll Intervall deutlich erhöhen und bin nun bei 25 oder 30 Sekunden.
