### ISSUE TITLE
core:LightIntensityState editable?

### ISSUE THREAD

**Issue by suspect80** [Excodibur/ioBroker.tahoma#160]
first of all, many many thanks for the maintenance of this adapter.

I have LED lights that I can dim via tahoma app in %. in the adapter is also displayed under core:LightIntensityState the percentage value. With my shutters I can set the percentage of opening via the adapter under core:TargetClosureState. Would this theoretically work with the LED lights? If so, can you add this to the adapter? I would also like to support the project financially.

thank you so much.

**Comment by Excodibur** [comment]
Hi,

positive feedback is all the support that I need for now. 😄 Perhaps the colleagues at https://www.iobroker.net/ that do most of the heavy lifting could use a 🍺 though.

I created a new release https://github.com/Excodibur/ioBroker.tahoma/releases/tag/v0.8.0 that should include this feature. You can install it already directly from Github, or later also from BETA repository.

Please check if it works for you.

**Comment by suspect80** [comment]
thank you. it works perfectly.
