### ISSUE TITLE
Missing command Buttons for rts shutters (deviceURL problem?)

### ISSUE THREAD

**Issue by Tscheffson** [Excodibur/ioBroker.tahoma#171]
I just started working with this adapter using the somfy connectivity kit. I have 3 rts and one io shutter which I wanted to implement into the adapter. All 4 shutters were added to my states, unfortunately, the rts shutters did not had any commands like "up", "down" or "stop"
so I was unable to control them.

I think I already found the problem. The deviceURL of the shutters all starts with "ogp" (one example "ogp://2105-1814-0785/52"). If I look correctly in the tahoma.js file, the commands are only added if the deviceURLs start with "io:" or "rts:", so I added "ogp:" and now the commands for the rts shutters are available and are also working. Here are my changes (even though I think this is only a semi-good workaround cause I guess it would create these commands for all devices):

    // commands
    for (const commandKey in deviceData.definition.commands) {
        const command = deviceData.definition.commands[commandKey];

        // nparams for commands indicates how may parameters a command expects

        if ((deviceData.deviceURL.startsWith("io:") && (command.nparams === 0)) ||
            (deviceData.deviceURL.startsWith("rts:") && (command.nparams <= 1)) ||
            (deviceData.deviceURL.startsWith("ogp:") && (command.nparams <= 1))) {
            controller.createOrUpdateState(name + ".commands." + command.commandName, false, {
                "type": "boolean",
                "read": true,
                "write": true,
                "role": "button"
            });

And here with marked changes:
![grafik](https://user-images.githubusercontent.com/71145272/196891373-a4b74d14-68ba-470b-9b90-61a61d24d706.png)

**Comment by Excodibur** [comment]
Thanks for reporting the issue. I included it in https://github.com/Excodibur/ioBroker.tahoma/releases/tag/v0.9.0 now.
