### ISSUE TITLE
Warning message about missing objects in the state

### ISSUE THREAD

**Issue by sly-1** [Excodibur/ioBroker.tahoma#19]
Somfy has updated Tahoma to version 2.20 today (March 23, 2021).  
Since then, I get these 2 warnings in the log file for each device every 25 seconds: 

1. `State "tahoma.0.devices.xxxxxxxxx.states.io:PriorityLockOriginatorState" has no existing object, this might lead to an error in future versions`

2. `State "tahoma.0.devices.xxxxxxxxx.states.io:PriorityLockLevelState" has no existing object, this might lead to an error in future versions` 

Can this be related to the TaHoma update? 
Can you take a look at this and correct it in the adapter if possible? 
Thanks for your effort. 

**Versions:**
 - Adapter version: 0.3.3
 - JS-Controller version: 3.2.13
 - Node version: v12.20.1
 - Operating system: Raspbian GNU/Linux 10 (buster)

**Comment by Kaiman77** [comment]
Same thing here on a Docker Synology installation.
I also assume a connection to the Tahoma update

**Comment by DirtyAtze** [comment]
Same problem, installation is on a Pi4.
Everything updated to latest stable Versions.

**Comment by SadoTron** [comment]
Same here.

- Adapter version: 0.3.3
- JS-Controller: 3.2.16
- Node.js: 12.22.0
- OS: Ubuntu 18.04 Server
 
Is there any chance to get rid of those warnings - maybe some workaround?

**Comment by TrifusOnline** [comment]
Same here.

Adapter version: 0.3.3
JS-Controller: 3.2.16
Node.js: 12.22.0

**Comment by mark77-DE** [comment]
As a workaround I have created the data points manually as type of "string".
Don't know if this is correct, but the warning messages for this error disappear.

**Comment by Excodibur** [comment]
It seems like this warning is thrown as part of a check with JS-Controller 3.2 onwards. I'll investigate it.

**Comment by Excodibur** [comment]
So far the issue did not reoccur on my end. It could potentially have been fixed with release 0.5.2 already, but it is hard for me to reproduce it. If it happens again, please reopen the ticket and send DEBUG logs (Howto enable: https://github.com/Excodibur/ioBroker.tahoma/issues/17#issuecomment-929961746) to me via mail ([excodibur-iobroker@posteo.de](mailto:excodibur-iobroker@posteo.de).), so I can dig deeper.
