### ISSUE TITLE
core:DeploymentState mit einbauen

### ISSUE THREAD

**Issue by integer63** [Excodibur/ioBroker.tahoma#2]
Einige meiner Antriebe habe den Datenpunkt DeploymentState anstelle ClosureState:
![DeploymentState](https://user-images.githubusercontent.com/35612711/72559954-4c0f0200-38a6-11ea-9125-6537d2b6f54a.png)
Kann man das noch einbauen?

**Comment by StrathCole** [comment]
Okay, muss ich übersehen haben. Mache ich direkt.

**Comment by StrathCole** [comment]
Bitte einmal testen. Ich habe das Handling der Zustände eingefügt.

**Comment by integer63** [comment]
DeploymentState funktioniert jetzt auch einwandfrei! Vielen Dank!
