### ISSUE TITLE
Missing states for up and down

### ISSUE THREAD

**Issue by uwe72** [Excodibur/ioBroker.tahoma#20]
@StrathCole 

In order to bring the roller shutter up and down i am missing the states. Last year i was able to do this within ioBroker. Today there are no more such states up and down. Thas all what i have for my RTS shutter.

![image](https://user-images.githubusercontent.com/61848539/113609983-d333cb80-964c-11eb-9311-ac3ea6ac431f.png)

**Comment by mariusbach** [comment]
you can add them yourself, I did the same 2 days ago. Just copy the raw content from the identify or test command, create a new data object (+ sign on top of the object tree) and paste the copied raw content into it (replacing whatever has been created automatically) and change the command from xxxx.identify or xxxx.test to xxxx.up, xxxx.down, xxxx.my.

Works for me, just a bit of manual work.

**Comment by uwe72** [comment]
> you can add them yourself, I did the same 2 days ago. Just copy the raw content from the identify or test command, create a new data object (+ sign on top of the object tree) and paste the copied raw content into it (replacing whatever has been created automatically) and change the command from xxxx.identify or xxxx.test to xxxx.up, xxxx.down, xxxx.my.
> 
> Works for me, just a bit of manual work.

you mean i just have to create the states manually? I will try this. At the moment i have another problem that i get a 401 http error while logging in through the adapter. This somfy things sucks a bit, sorry :-)

**Comment by mariusbach** [comment]
yes manually. I just copied one of the identify or test command to have a starting point and then created a new object manually, copy-paste into it the content and change the command to .up, .down, .my 

I haven't had the 401 yet :) can't help for this one.

**Comment by uwe72** [comment]
thanks a lot. I will try it....

**Comment by mariusbach** [comment]
I would prefer to keep this issue open since it should be automatic if possible, saving tedious manual work :)

**Comment by uwe72** [comment]
ok, u r right

**Comment by uwe72** [comment]
@mariusbach 

You did a copy&paste of the raw state, right?

{
  "type": "state",
  "common": {
    "type": "boolean",
    "read": true,
    "write": true,
    "role": "button",
    "name": "test"
  },
  "native": {},
  "from": "system.adapter.tahoma.0",
  "user": "system.user.admin",
  "ts": 1617659419691,
  "_id": "tahoma.0.devices.10.commands.test",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}

Then you just modified the "test" twice? or u modified other parts of the raw state?

**Comment by uwe72** [comment]
@mariusbach worked like you said. thanks!

**Comment by uwe72** [comment]
@mariusbach i don't know if you saw also this thread:
https://github.com/StrathCole/ioBroker.tahoma/issues/17

It is an alternative solutions.

**Comment by mariusbach** [comment]
Thanks, I haven't seen that one. So along with up, down, my there are commands stop, open, close it seems. I tried stop and it works. Open and close probably have the same effect as up and down, I'll try. They might be uninterruptible by stop, let's see :)
