### ISSUE TITLE
Adapter throws errors: "certificate has expired, request path: login with payload: +++redacted+++"

### ISSUE THREAD

**Issue by MichaelSchaaf999** [Excodibur/ioBroker.tahoma#205]
**Describe the bug**  
The adapter does not connect, throws an error instead.

**Expected behavior**  
Adapter exptected to login to Tahoma without errors.

**Screenshots & Logfiles**  
n.a.

**Versions:**  
 - Adapter version: 0.10.1
 - JS-Controller version: 4.0.24
 - Node version: 14.20.0
 - Operating system: Debian Linux 10

**Additional context**  
worked before most of the time

**Comment by Excodibur** [comment]
To me it looks like it is a problem on Somfy's side. It seems like they let the certificate of their webservice tahomalink.com expire.

![image](https://user-images.githubusercontent.com/70700967/216649712-ca046021-a242-443f-a796-f16dcb8c4ccf.png)

Apparently they registered a new certificate on 01.02.2023, so the error should be gone by now. Please check it.
