### ISSUE TITLE
DP Moving wird Wert nicht geändert

### ISSUE THREAD

**Issue by Supermario-21** [Excodibur/ioBroker.tahoma#212]
Hallo, bei den Datenpunkte:
tahoma.0.devices.xxxxxx.states.core:MovingState
tahoma.0.devices.xxxxxx.states.moving
wird der Wert nicht geändert, obwohl das Gerät fährt!
![image](https://user-images.githubusercontent.com/104907692/226299454-fc706e08-cce6-488a-bf12-60627a8a000f.png)
![image](https://user-images.githubusercontent.com/104907692/226299531-0f69cd70-9b3e-4108-a260-a82ac94ecebe.png)

**Comment by Excodibur** [comment]
Bitte probiere es nochmal mit dem letzten Update: https://github.com/Excodibur/ioBroker.tahoma/releases/tag/v0.10.2

Bei Einsatz der lokalen API wird `moving` zwar nicht richtig funktionieren (da die lokale API nicht so viele Event-Updates liefert wie die online-Variante), aber `core:MovingState` sollte jetzt zumindest via `true`/`false` indizieren, ob das Rollo sich bewegt.
