### ISSUE TITLE
hugh information delay on using manuell wall switches

### ISSUE THREAD

**Issue by ghooser83** [Excodibur/ioBroker.tahoma#232]
Hallo together,

i wants to thank you for this pretty usefull adapter. It keeps helping me in summer time to cool our house down.

I have recogniesed a problem, and i would like to know if i have something missconfigured.

The Problem:
Everything works fine and informations are updated in a reasonable time. But wenn i use our wall switches which are connected to our sunshade motors it took 1 hour to get the information that the position of our shades have changed. If i command a new percentage value via ioBroker/your app, i get it in 20 seconds. Is this behavior normal or is there a posibility to get the information faster?

Thanks alot in advance.

**Comment by Excodibur** [comment]
Hi,

to what number did you set the `Polling interval` in the adapter configuration? This should influence how often the adapter checks for updates on states.
