### ISSUE TITLE
Exceptions when using adapter with connexxoon box with local API

### ISSUE THREAD

**Issue by Kaiman77** [Excodibur/ioBroker.tahoma#241]
The Somfy Connexxoon Box also supports the local API now.
When using it with the adapter, the following logfile happens with every action performed.
The changes still work (awning moves) but there is an exception happening
When using the cloud API (removing the key in the local API tab), everything works fine.

![grafik](https://github.com/Excodibur/ioBroker.tahoma/assets/47158634/577f926c-7763-4cf3-8f0e-b14e9792de27)

**Versions:**  
 - Adapter version: tried it with 0.10.0, 0.10.1 and 0.10.2
 - JS-Controller version: 4.0.24
 - Node version: v18.15.0
 - Operating system: Docker on Synology NAS

**Comment by Excodibur** [comment]
Does this issue also occur, if you delete the adapter instance, create a new one and connect to the local API right away? I am wondering if the online API delivered some state information in a different format initially and the when switching to the local API that one expects a different format - just a guess though.

If that does not help, please provide some [DEBUG logs](https://github.com/Excodibur/ioBroker.tahoma/blob/master/FAQ.md#the-adapter-crashes-when-it-loads-devices-from-tahoma-or-sets-up-corresponding-states-incorrectly-what-can-i-do-to-help-the-developers-to-fix-this) to me, so I can check it more in detail.

**Comment by Kaiman77** [comment]
ok, that was too easy :-)
A new installation works just fine, I'll guess we can close this. 
Thanks for the hint.
