### ISSUE TITLE
What about the frequent log entry that a search "folder" cannot be found in "system"?

### ISSUE THREAD

**Issue by MichaelSchaaf999** [Excodibur/ioBroker.tahoma#25]
<img width="679" alt="image" src="https://user-images.githubusercontent.com/53481090/118593850-ad9bf500-b7a8-11eb-92bd-1ca293358acb.png">

**Comment by MichaelSchaaf999** [comment]
Today this can be found in the log as well:



tahoma.0 | 2021-05-27 06:09:04.556 | warn | (9277) Body: {"errorCode":"UNSPECIFIED_ERROR","error":"No registered event listener"}
tahoma.0 | 2021-05-27 06:09:04.556 | warn | (9277) Response: {"statusCode":400,"body":{"errorCode":"UNSPECIFIED_ERROR","error":"No registered event listener"},"headers":{"date":"Thu, 27 May 2021 04:09:03 GMT","server":"overkiz","strict-transpor
tahoma.0 | 2021-05-27 06:09:04.556 | warn | (9277) error during tahomalink request: null, request path: events/aab95340-ac10-3e01-5680-b8ebaef61060/fetch with payload:{}
tahoma.0 | 2021-05-27 06:09:02.898 | warn | (9277) error during tahomalink request: undefined -&gt;401 retry events/aab95340-ac10-3e01-5680-b8ebaef61060/fetch
tahoma.0 | 2021-05-27 06:09:02.894 | warn | (9277) error during tahomalink request: undefined -&gt;401 retry /setup/devices/states/refresh


<br class="Apple-interchange-newline" style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;">

What can I do to resolve this?

**Comment by MichaelSchaaf999** [comment]
adding the messages from today...


Quelle | Zeit | warn | Nachricht
-- | -- | -- | --
tahoma.0 | 2021-05-28 13:40:05.177 | warn | Body: {"errorCode":"UNSPECIFIED_ERROR","error":"No registered event listener"}
tahoma.0 | 2021-05-28 13:40:05.177 | warn | Response: {"statusCode":400,"body":{"errorCode":"UNSPECIFIED_ERROR","error":"No registered event listener"},"headers":{"date":"Fri, 28 May 2021 11:40:04 GMT","server":"overkiz","strict-transport-security":"max-age=31536000; includeSubDomains","content-type":"application/json;charset=UTF-8","connection":"close","transfer-encoding":"chunked"},"request":{"uri":{"protocol":"https:","slashes":true,"auth":null,"host":"www.tahomalink.com","port":443,"hostname":"www.tahomalink.com","hash":null,"search":null,"query":null,"pathname":"/enduser-mobile-web/enduserAPI/events/b13359ca-ac10-3e01-5680-b8ebdf68225e/fetch","path":"/enduser-mobile-web/enduserAPI/events/b13359ca-ac10-3e01-5680-b8ebdf68225e/fetch","href":"https://www.tahomalink.com/enduser-mobile-web/enduserAPI/events/b13359ca-ac10-3e01-5680-b8ebdf68225e/fetch"},"method":"POST","headers":{"User-Agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36","cookie":"JSESSIONID=F1AA27B1E984110A33EAF03A987F31EA","accept":"application/json","content-type":"application/json","content-length":2}}}
tahoma.0 | 2021-05-28 13:40:05.177 | warn | error during tahomalink request: null, request path: events/b13359ca-ac10-3e01-5680-b8ebdf68225e/fetch with payload:{}
tahoma.0 | 2021-05-28 13:40:03.232 | warn | error during tahomalink request: undefined -&gt;401 retry events/b13359ca-ac10-3e01-5680-b8ebdf68225e/fetch
tahoma.0 | 2021-05-28 13:40:03.226 | warn | error during tahomalink request: undefined -&gt;401 retry /setup/devices/states/refresh

**Comment by Excodibur** [comment]
When does this error occur for you? Right after adapter-start, or hours or even days after the adapter was started?

In your logs I see that you get a 401 (unauthorized) error before you get this error about "No registered event listener". It could be that Tahoma assumes the adapter is not authorized (anymore) to run the subsequent query. If that is the case I need to know details from you regarding my initial question, so I can make an assumption an potentially provide a fix.

**Comment by MichaelSchaaf999** [comment]
Thx for your patience: After the last updates this message did not return.
