### ISSUE TITLE
iobroker adapter crashes

### ISSUE THREAD

**Issue by rofo68** [Excodibur/ioBroker.tahoma#259]
I am trying to add my Somfy thermostats to iobroker. If I see it correctly, there is only the state "tahoma.0.devices.Wohnzimmer_W_Heizung.states.core:TargetTemperatureState" which is included with the role level.blind and is writable/changeable. Here a percentage value can be entered. If I change the value, there is an error in the adapter and it crashes then. In the log you can see the following:
![image](https://github.com/Excodibur/ioBroker.tahoma/assets/14974106/99fcb1be-a812-4cfc-8869-21372ab893d9)

**Comment by pestho** [comment]
I added the Netatmo Sensor and Hue Lights and have the Same Problem

**Comment by Excodibur** [comment]
Please provide some DEBUG logs to allow me to check the issue further (https://github.com/Excodibur/ioBroker.tahoma/blob/master/FAQ.md#the-adapter-crashes-when-it-loads-devices-from-tahoma-or-sets-up-corresponding-states-incorrectly-what-can-i-do-to-help-the-developers-to-fix-this).
