### ISSUE TITLE
SignalQualityState" has to be type "number" but received type "string"

### ISSUE THREAD

**Issue by 9Mad-Max5** [Excodibur/ioBroker.tahoma#260]
**Describe the bug**  
State value to set for "tahoma.0.devices.Connectivity_kit-box.states.core:SignalQualityState" has to be type "number" but received type "string"
State value to set for "tahoma.0.location.postalCode" has to be type "string" but received type "number"

**To Reproduce**  
Start adapter

**Expected behavior**  

**Screenshots & Logfiles**  
Ideally, set the adapter to DEBUG-loglevel and provide the logfiles for it as well. **Before** providing the logfiles, please check entries marked with __Response:__ do not contain any personalized data, like your private address (under __location__), or similar.

**Versions:**  
 - Adapter version: <adapter-version>
 - JS-Controller version: <js-controller-version> 
 - Node version: <node-version> 
 - Operating system: <os-name>

starting. Version 0.10.2 in /opt/iobroker/node_modules/iobroker.tahoma, node: v18.17.1, js-controller: 4.0.24
[START] Starting adapter tahoma v0.10.2.3
Configured polling interval: 60000

**Additional context**  
Those two messages always occur in the protokoll.

**Comment by Excodibur** [comment]
Please Please provide some DEBUG logs to allow me to check the issue further (https://github.com/Excodibur/ioBroker.tahoma/blob/master/FAQ.md#the-adapter-crashes-when-it-loads-devices-from-tahoma-or-sets-up-corresponding-states-incorrectly-what-can-i-do-to-help-the-developers-to-fix-this).
