### ISSUE TITLE
State value to set for "tahoma.0.devices.Rollladen_Terasse.states.core:MovingState" has to be type "boolean" but received type "string" 

### ISSUE THREAD

**Issue by klausiob** [Excodibur/ioBroker.tahoma#313]
I have a Somfy Switch and get this "info" with Adapter 0.10.2. Values received are "false" or "true".

**Comment by Excodibur** [comment]
Does the error still persist, if you remove the folder `tahoma` in the _Object_-view in ioBroker Admin GUI and restart the adapter?
