### ISSUE TITLE
Log Warn Message "tahoma has an invalid jsonConfig"

### ISSUE THREAD

**Issue by Matt77CHE** [Excodibur/ioBroker.tahoma#333]
After adapter installing, I recognized a warn message in Log file:

`tahoma has an invalid jsonConfig: [{"instancePath":"/items/basicSettingsTab","schemaPath":"#/properties/items/patternProperties/%5E.%2B/allOf/8/then/additionalProperties","keyword":"additionalProperties","params":{"additionalProperty":"i18n"},"message":"must NOT have additional properties"},{"instancePath":"","schemaPath":"#/if","keyword":"if","params":{"failingKeyword":"then"},"message":"must match \"then\" schema"}]`

**Versions:**  
 - Adapter version: 0.10.3
 - JS-Controller version: 5.0.19
 - Node version: 18.19.0
 - Operating system: Linux

**Comment by mcm1957** [comment]
i18n attribute is only valid at top level and at custom component entry according to schema.md
https://github.com/Excodibur/ioBroker.tahoma/blob/f6c12259fdfea1602a6473a8b39c8b6113b21275/admin/jsonConfig.json#L40
https://github.com/Excodibur/ioBroker.tahoma/blob/f6c12259fdfea1602a6473a8b39c8b6113b21275/admin/jsonConfig.json#L60

https://github.com/ioBroker/ioBroker.admin/blob/master/packages/jsonConfig/SCHEMA.md

So those two lines should be removed in my opinnion.

**Comment by Excodibur** [comment]
Thanks for reporting the issue and for the hint. It should be fixed with https://github.com/Excodibur/ioBroker.tahoma/releases/tag/v0.10.4 now. Please check if the issue still occurs.
