### ISSUE TITLE
version 0.5.0.3 does not work

### ISSUE THREAD

**Issue by Moormerlander** [Excodibur/ioBroker.tahoma#52]
I updated to version 0.5.03 today and since then I get this error and no device is working anymore:

error during tahomalink request: Error: connect ETIMEDOUT 178.32.15.131:443, request path: login with payload: +++redacted+++

**Comment by hmpft** [comment]
Tahomalink seems to have a server issue currently

At least in germany:

13.10.2021: Aktuelle Information zu TaHoma
Liebe Somfy Kunden,

aufgrund technischer Probleme ist TaHoma aktuell nicht erreichbar.
Hinterlegte Automatiken werden weiterhin ausgeführt. Bitte nutzen Sie zur manuellen Bedienung vorübergehend die Vor-Ort-Steuerungen.
Unsere IT arbeitet bereits mit Hochdruck an einer Lösung.

Vielen Dank für Ihr Verständnis,
Somfy Privatkundenservice

https://www.somfy.de/hilfe-center

**Comment by Moormerlander** [comment]
Die Probleme bei Somfy sind wohl behoben und auch die neue Version funktioniert. 
Vielen Dank für den Hinweis! 
Ich schließe dieses Problem.
