### ISSUE TITLE
Login retry not pausing

### ISSUE THREAD

**Issue by StrathCole** [Excodibur/ioBroker.tahoma#6]
Login is retried every (few) seconds instead of waiting for 2 minutes as intended.

**Comment by uwe72** [comment]
I cannot connect to thaoma with my adapter, even login/password are correct:


tahoma.0 | 2020-05-13 13:43:13.510 | info | (32002) Login failed three times, waiting 2 minutes before retrying.
-- | -- | -- | --
tahoma.0 | 2020-05-13 13:43:13.510 | warn | (32002) error during tahomalink request: undefined ->401 retry login

**Comment by jb-home** [comment]
I am facing similar issue.
I suspect that the poll interval is too fast and login is getting blocked. I am now trying to figure out which polling interval works 24/7. I started with 15000, than 20000, than 30000, than 60000 and now I am trying 120000. But this interval is already too long for my taste.

If this error occurs, I have to pause the adapter for some time. After reactivation it is again working fine. But I did not record the timeframe it took to 'unblock' the login attempt.

**Comment by CloudJunkie** [comment]
After initial successful login, I get this messages:
"Login failed three times, waiting 2 minutes before retrying."
"error during tahomalink request: undefined ->401 retry login"
This repeats every 1-5 second. The adapter is just not waiting 2 minutes.
Deactivating the adapter for a while solves it for some hours, Then it starts again

**Comment by MichaelSchaaf999** [comment]
same issue here...   there is another thread already with the same problem.

**Comment by Moormerlander** [comment]
This issue already exists for a long time, but nobody cares. I am a programmer, but not for this kind of software unfortunately otherwise I would like to fix it because it's so annoying.

**Comment by Excodibur** [comment]
Please check if the issue still exists with release 0.4.0.

If you use the new Admin 5 GUI, you should now also be able to adjust the reconnect-behaviour more directly.

**Comment by MichaelSchaaf999** [comment]
how to update to 0.4.0?

**Comment by Excodibur** [comment]
There are multiple options:

- If you are retrieving adapter from BETA repository update it directly via `iobroker update && iobroker update` or in Admin GUI
- Install directly from Github

**Comment by MichaelSchaaf999** [comment]
BETA does not show 0.4.0:
<img width="774" alt="grafik" src="https://user-images.githubusercontent.com/53481090/128546419-43285247-9515-4260-b2f8-e3261d1a484f.png">

**Comment by Excodibur** [comment]
Did you try to check for new updates in IOBroker? For me it is definitely there:
![image](https://user-images.githubusercontent.com/70700967/128556455-464d3a9a-cfc1-4275-97ca-d2cfda3703e0.png)

**Comment by MichaelSchaaf999** [comment]
seen it now, thanks. Updated. 0.4.2
