### ISSUE TITLE
enhancement: control temperature for heating

### ISSUE THREAD

**Issue by j-r79** [Excodibur/ioBroker.tahoma#62]
Hello,

i use your adapter to control my tahoma-devices, but i can not change the temperature for my heaters. The devices are there and show the correct data, but i can not change the temperature.

Like the shutters, i assume, that i change core:TargetTemperatureState to set the temperature and see the current temperature in core:TemperatureState.

Maybe you can update your adapter, so that core:TargetTemperatureState can be changed?

Thank you!

**Comment by j-r79** [comment]
![image](https://user-images.githubusercontent.com/5916790/141692503-5f4a58eb-ba50-44b9-918e-65986dd252a7.png)

**Comment by Excodibur** [comment]
Yes I agree, it should be made changeable.

I updated the code and built a new release (https://github.com/Excodibur/ioBroker.tahoma/releases/tag/v0.5.1) for it. Please give it a try by either installing directly from Github, or directly from ioBroker BETA repository/NPM.

**Comment by j-r79** [comment]
Thank you, the value can now be changed in iobroker, but it has no effect to my heating. Here is the log, when i change the value:

`2021-11-18 13:16:42.698 - silly: tahoma.0 (30948) States user redis pmessage tahoma.0.*/tahoma.0.devices.Bad.states.core:TargetTemperatureState:{"val":12,"ack":false,"ts":1637237802693,"q":0,"from":"system.adapter.admin.0","user":"system.user.admin","lc":1637237802693}
2021-11-18 13:16:42.699 - debug: tahoma.0 (30948) stateChange tahoma.0.devices.Bad.states.core:TargetTemperatureState {"val":12,"ack":false,"ts":1637237802693,"q":0,"from":"system.adapter.admin.0","user":"system.user.admin","lc":1637237802693}
2021-11-18 13:16:42.700 - debug: tahoma.0 (30948) id=devices.Bad.states.core:TargetTemperatureState
2021-11-18 13:16:42.700 - debug: tahoma.0 (30948) StateChange: ["devices.Bad.states.core:TargetTemperatureState",12]
2021-11-18 13:16:51.570 - debug: tahoma.0 (30948) Starting state polling
2021-11-18 13:16:51.571 - debug: tahoma.0 (30948) Refreshing device states.
2021-11-18 13:16:51.572 - debug: tahoma.0 (30948) POST request on https://www.tahomalink.com/enduser-mobile-web/enduserAPI/setup/devices/states/refresh with payload:{}
2021-11-18 13:16:51.665 - debug: tahoma.0 (30948) Response: {}
2021-11-18 13:16:51.666 - debug: tahoma.0 (30948) POST request on https://www.tahomalink.com/enduser-mobile-web/enduserAPI/events/xxxxx/fetch with payload:{}
2021-11-18 13:16:51.737 - debug: tahoma.0 (30948) Response: [{"timestamp":1637237811653,"gatewayId":"xxxxx","name":"GatewaySynchronizationStartedEvent"}]
2021-11-18 13:16:51.737 - debug: tahoma.0 (30948) events/xxxxx/fetchFetched Data [{"timestamp":1637237811653,"gatewayId":"xxxxx","name":"GatewaySynchronizationStartedEvent"}]`

**Comment by Excodibur** [comment]
Hmm, your log-messages look OK. 

The thing is that I don't own a heating-controller by Somfy myself, so I cannot really reproduce the issue on my side.

Does the problem appear with any other Somfy device, or is it just your thermostat causing issues? Can it be modified directly via Tahoma App?

**Comment by j-r79** [comment]
Yes,

all other devices (shutter, power-switch socket, power-switch light) do work. 

It is not a somfy-controller, it is a honeywell, which can be controlled via tahoma. I can change the temperature via tahomaconnect (web-app) and in the mobile app. Both are sent via the tahoma-box to the honeywell box and then my heaters are turned on/off.

It would be nice, if i could change the temperature via iobroker, so i could change the temperature within my scripts, but i can still live even without that feature. :-)

**Comment by Excodibur** [comment]
Hmm, I am afraid I can't do much more here myself to reproduce/fix, as your setup seems pretty unique.

In parallel I am taking a look at writing an adapter to utilize the official Somfy API (https://github.com/Excodibur/ioBroker.somfy-open-api), which might work better for this scenario. Unfortunately, I am currently stuck with authorization, since t.b.h. it seems like Somfy provides a really broken service there without much support. So even if I get it to work, I am not sure if I can really recommend on using there official API in terms of stability.

**Comment by j-r79** [comment]
Good to hear that you are working on the "official" api, wish you the best. 

The honeywell devices are from the early days of tahoma, the first supported "not-somfy"/"not-io-homecontrol" devices. 

When i was looking through the net i found a possible solution. homeassistent seems to have a plugin which can control the honeywell-devices directly. Maybe i will install HA to test this.

**Comment by Excodibur** [comment]
@j-r79 I made some code changes with Commit https://github.com/Excodibur/ioBroker.tahoma/commit/7c3a6f727af2c5ab42e39d6ede72ab4c922a1a55 specifically to change TargetTemperatureState, but I could not test it myself, since i don't have a Somfy thermostat. Feel free to check the latest adapter code (install directly from Github, for now) for the new temperature support

**Comment by j-r79** [comment]
Thank you for your effort, but my devices started to fail. The sensors of the devices always showed 18 degree, no matter if the real temperature was 5 or 25. My idea was to put the target temperature with iobroker to an value higher or less then 18 to start or stop heating, controlled by an aqara sensor, but i ditched this idea, because i had no possibility to change the targetTemperature. I replaced the devices with homematic.

**Comment by Excodibur** [comment]
Thanks for your feedback! I will add the functionality to the next release anyways, just in case someone might need it.
