### ISSUE TITLE
Error: getaddrinfo EAI_AGAIN www.tahomalink.com

### ISSUE THREAD

**Issue by Basti189** [Excodibur/ioBroker.tahoma#71]
<html>
<body>

tahoma.0 | 2021-12-21 11:23:16.556 | warn | error during tahomalink request: Error: getaddrinfo EAI_AGAIN www.tahomalink.com, request path: setup/gateways/2005-XXXX-XXXX with payload:{}
-- | -- | -- | --
tahoma.0 | 2021-12-21 11:23:08.494 | warn | error during tahomalink request: Error: getaddrinfo EAI_AGAIN www.tahomalink.com, request path: setup/gateways/2005-XXXX-XXXXwith payload:{}
tahoma.0 | 2021-12-21 11:23:00.428 | warn | error during tahomalink request: Error: getaddrinfo EAI_AGAIN www.tahomalink.com, request path: setup/gateways/2005-XXXX-XXXXwith payload:{}
tahoma.0 | 2021-12-21 11:22:52.364 | warn | error during tahomalink request: Error: getaddrinfo EAI_AGAIN www.tahomalink.com, request path: setup/gateways/2005-XXXX-XXXXwith payload:{}

</body>
</html>

Etwa zwei Tage läuft der Adapter ohne Probleme, dann wird das Logfile im Bereich von wenigen Sekunden von dieser Meldung geflutet und die Rollläden können nicht mehr gesteuert werden. Hab auch schon die Werte deutlich höher eingestellt. Gibt es da noch eine Möglichkeit etwas zu machen?

Gerät ist eine Tahoma Switch

Danke für deine Arbeit und das es eigentlich toll funktioniert, obwohl Somfy hier einige Steine in den Weg legt...

**Comment by Excodibur** [comment]
**EAI_AGAIN** deutet eigentlich immer auf allgemeine Netzwerkprobleme hin, da die Domäne tahomalink.com nicht aufgelöst werden konnte. D.h. der Adapter kann hier selbst nicht wirklich zur Problemlösung beitragen.

Die einfachste Möglichkeit um die Log-Flut zu minimieren, wäre _Delay after failed login_ relativ hoch zu setzen, z.b. auf 3600 Sekunden (1 Stunde Wartezeit nach fehlgeschlagenen Wiederverbindungsversuchen), in der Hoffnung das Netzwerkprobleme danach verschwunden sind. In diesem Zeitraum ist der Adapter zur Steuerung natürlich relativ nutzlos.
