### ISSUE TITLE
Adapter stoped working

### ISSUE THREAD

**Issue by dagoellner** [Excodibur/ioBroker.tahoma#85]
Tahoma adapter stoped working in IOBRoker.

2022-01-31 07:14:10.520 | warn | error during tahomalink request: Error: certificate has expired, request path: login with payload: +++redacted+++

2022-01-31 07:14:06.252 | warn | error during tahomalink request: Error: certificate has expired, request path: setup/gateways/1238-1010-7619 with payload:{}
-- | -- | --
tahoma.0 | 2022-01-31 07:14:06.237 | warn | error during tahomalink request: Error: certificate has expired, request path: setup/gateways/1238-1010-7619 with payload:{}
tahoma.0 | 2022-01-31 07:14:06.234 | warn | error during tahomalink request: Error: certificate has expired, request path: setup/gateways/1238-1010-7619 with payload:{}
tahoma.0 | 2022-01-31 07:14:06.226 | warn | error during tahomalink request: Error: certificate has expired, request path: setup/gateways/1238-1010-7619 with payload:{}
tahoma.0 | 2022-01-31 07:14:05.618 | warn | error during tahomalink request: Error: certificate has expired, request path: events/a18f2938-98e4-e192-3324-f085256f69be/fetch with payload:{}
tahoma.0 | 2022-01-31 07:14:00.648 | warn | error during tahomalink request: Error: certificate has expired, request path: events/a18f2938-98e4-e192-3324-f085256f69be/fetch with payload:{}
tahoma.0 | 2022-01-31 07:13:55.614 | warn | error during tahomalink request: Error: certificate has expired, request path: events/a18f2938-98e4-e192-3324-f085256f69be/fetch with payload:{}
tahoma.0 | 2022-01-31 07:13:50.611 | warn | error during tahomalink request: Error: certificate has expired, request path: events/a18f2938-98e4-e192-3324-f085256f69be/fetch with payload:{}
tahoma.0 | 2022-01-31 07:13:45.605 | warn | error during tahomalink request: Error: certificate has expired, request path: events/a18f2938-98e4-e192-3324-f085256f69be/fetch with payload:{}
tahoma.0 | 2022-01-31 07:13:40.607 | warn | error during tahomalink request: Error: certificate has expired, request path: events/a18f2938-98e4-e192-3324-f085256f69be/fetch with payload:{}
tahoma.0 | 2022-01-31 07:13:36.339 | warn | error during tahomalink request: Error: certificate has expired, request path: setup/gateways/1238-1010-7619 with payload:{}
tahoma.0 | 2022-01-31 07:13:36.327 | warn | error during tahomalink request: Error: certificate has expired, request path: setup/gateways/1238-1010-7619 with payload:{}
tahoma.0 | 2022-01-31 07:13:36.313 | warn | error during tahomalink request: Error: certificate has expired, request path: setup/gateways/1238-1010-7619 with payload:{}
tahoma.0 | 2022-01-31 07:13:36.299 | warn | error during tahomalink request: Error: certificate has expired, request path: setup/gateways/1238-1010-7619 with payload:{}
tahoma.0 | 2022-01-31 07:13:36.244 | warn | error during tahomalink request: Error: certificate has expired, request path: setup/gateways/1238-1010-7619 with payload:{}
tahoma.0 | 2022-01-31 07:13:36.207 | warn | error during tahomalink request: Error: certificate has expired, request path: setup/gateways/1238-1010-7619 with payload:{}
tahoma.0 | 2022-01-31 07:13:36.193 | warn | error during tahomalink request: Error: certificate has expired, request path: setup/gateways/1238-1010-7619 with payload:{}
tahoma.0 | 2022-01-31 07:13:36.189 | warn | error during tahomalink request: Error: certificate has expired, request path: setup/gateways/1238-1010-7619 with payload:{}
tahoma.0 | 2022-01-31 07:13:36.182 | warn | error during tahomalink request: Error: certificate has expired, request path: setup/gateways/1238-1010-7619 with payload:{}
tahoma.0 | 2022-01-31 07:13:35.603 | warn | error during tahomalink request: Error: certificate has expired, request path: events/a18f2938-98e4-e192-3324-f085256f69be/fetch with payload:{}
tahoma.0 | 2022-01-31 07:13:30.601 | warn | error during tahomalink request: Error: certificate has expired, request path: events/a18f2938-98e4-e192-3324-f085256f69be/fetch with payload:{}
tahoma.0 | 2022-01-31 07:13:25.599 | warn | error during tahomalink request: Error: certificate has expired, request path: events/a18f2938-98e4-e192-3324-f085256f69be/fetch with payload:{}
tahoma.0 | 2022-01-31 07:13:20.596 | warn | error during tahomalink request: Error: certificate has expired, request path: events/a18f2938-98e4-e192-3324-f085256f69be/fetch with payload:{}
tahoma.0 | 2022-01-31 07:13:15.595 | warn | error during tahomalink request: Error: certificate has expired, request path: events/a18f2938-98e4-e192-3324-f085256f69be/fetch with payload:{}
tahoma.0 | 2022-01-31 07:13:14.406 | warn | https://www.tahomalink.com/enduser-mobile-web/enduserAPI/exec/9968ff63-ae91-45a8-b00c-1f58d4efe704
tahoma.0 | 2022-01-31 07:13:14.406 | warn | error during tahomalink request: Error: certificate has expired, request path: exec/9968ff63-ae91-45a8-b00c-1f58d4efe704 with payload:""

**Comment by andy6325** [comment]
Same error on my side :

```
- tahoma.0 | 2022-01-31 07:46:59.791 | info | Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
- tahoma.0 | 2022-01-31 07:46:59.790 | info | terminating
- tahoma.0 | 2022-01-31 07:46:59.786 | info | Got terminate signal TERMINATE_YOURSELF
- tahoma.0 | 2022-01-31 07:34:06.123 | warn | error during tahomalink request: Error: certificate has expired, request path: login with payload: +++redacted+++
- tahoma.0 | 2022-01-31 07:34:05.870 | info | Configured polling interval: 6000000
- tahoma.0 | 2022-01-31 07:34:05.868 | info | [START] Starting adapter tahoma v0.5.0.3
- tahoma.0 | 2022-01-31 07:34:05.799 | info | starting. Version 0.5.0 in /opt/iobroker/node_modules/iobroker.tahoma, node: v14.18.3, js-controller: 3.3.22
- tahoma.0 | 2022-01-31 07:34:00.494 | warn | error during tahomalink request: Error: certificate has expired, request path: login with payload: +++redacted+++
- tahoma.0 | 2022-01-31 07:34:00.480 | info | Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
- tahoma.0 | 2022-01-31 07:34:00.479 | info | terminating
- tahoma.0 | 2022-01-31 07:34:00.479 | warn | Error during logout: true
- tahoma.0 | 2022-01-31 07:34:00.478 | warn | error during tahomalink request: Error: certificate has expired, request path: logout with payload:{}
- More than 20x: | 2022-01-31 07:31:49.942 | warn | error during tahomalink request: Error: certificate has expired, request path: setup/gateways/1206-9168-8264 with payload:{}
```

Appeared after fist command has been send manually today.

**Comment by technicallife** [comment]
+1

Edit: ssl certificate from tahomalink.com run out of date - once they update it, it will work again

**Comment by andy6325** [comment]
Certificate has been updated. Issue can be closed. Valid until 1st of February 2023.

**Comment by dagoellner** [comment]
Danke!!!!
